version: '3.7'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fastladder_development
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/data:/var/lib/mysql
    #- ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
    - 3307:3306
  web:
    build:
      context: .
    command: /bin/sh -c "bundle install && rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      TZ: Asia/Tokyo
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node-modules:/app/node_modules/
      # - packs:/app/public/packs
      # - yarn-cache:/usr/local/share/.cache/yarn/v6
    stdin_open: true
    tty: true
    ports:
    - 3001:3000
    depends_on:
      - db
volumes:
  bundle:
  node-modules:
