name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:5.7.12
        env:
          TZ: Asia/Tokyo
          MYSQL_ROOT_PASSWORD: root

    container:
      image: ruby:2.6.6
      env:
        RAILS_ENV: test
        TZ: Asia/Tokyo

    steps:
    - uses: actions/checkout@v2

    - name: install middlewares
      run: |
        apt-get update -qq
        apt-get install -y nodejs build-essential curl apt-transport-https wget

    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Build and setup
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 9 --retry 3
        bundle exec rails db:create db:migrate

    - run: bundle exec rails spec
