name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.6.6
          - 2.7
          - 2.8.0-dev
    services:
      db:
        image: mysql:5.7.12
        env:
          TZ: Asia/Tokyo
          MYSQL_ROOT_PASSWORD: root
      webdriver_chrome:
        image: selenium/standalone-chrome

    container:
      image: ruby:${{ matrix.ruby }}
      env:
        RAILS_ENV: test
        SELENIUM_REMOTE_URL: http://webdriver_chrome:4444/wd/hub
        TZ: Asia/Tokyo

    steps:
    - uses: actions/checkout@v2

    - name: install middlewares
      run: |
        apt-get update -qq
        apt-get install -y nodejs build-essential curl apt-transport-https wget

    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: v1-${{ runner.os }}-${{ matrix.ruby }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          v1-${{ runner.os }}-${{ matrix.ruby }}-gems-

    - name: Build and setup
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 9 --retry 3
        bundle exec rails db:create db:migrate

    - run: bundle exec rails spec
